services:

  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: kromann
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pkea" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: "ghcr.io/ek-team-48/team-48-todo-backend/kr-backend:latest"
    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - /root/keys:/keys:ro

    environment:
      - spring.application.name=mysql
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=${DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

      - JWT_PUBLIC_KEY_PATH=/keys/public.key
      - JWT_PRIVATE_KEY_PATH=/keys/private.pem

    depends_on:
      mysql:
        condition: service_healthy


  frontend:
      # Hvis du har bygget lokalt: docker build -t kr-frontend:latest .
    image: "ghcr.io/ek-team-48/team-48-todo-frontend/kr-frontend:latest"
    depends_on:
      - backend
    ports:
      - "80:80"




volumes:
  mysql_data: