name: Test project and then Deploy Ubuntu Server Project

on:
  push:
    branches: [ "main" ]

jobs:
  ## First we build and test the application if it works. First with Docker and then with maven
  ## This is not necessary as the code is being tested on each branch
  ## - However, we would like a certain security before deploying to our server
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run docker test
        run: |
          docker compose up -d
          sleep 60
          docker ps -a
          docker logs $(docker ps -aq --filter name=app)
          curl -i http://127.0.0.1:8080/healthz
          docker compose down

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-


      - name: Build with Maven (tests + package)
        ## Changed package to clean verify as it's now test and pack the mvn to run
        run: mvn -B clean verify --file pom.xml

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/ek-team-48/team-48-todo-backend/kr-backend:latest .
          docker push ghcr.io/ek-team-48/team-48-todo-backend/kr-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}

        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          docker compose down
          docker compose pull
          docker compose up --build --detach
          "